import {StyleSheet} from 'react-native';
import {Colors} from '../constants/Colors';

export const styles = StyleSheet.create({
  component: {
    width: '100%',
    height: '100%',
  },
  accounts: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  divider: {
    marginTop: 32,
  },
  action: {
    backgroundColor: 'transparent',
  },
  listPad: {
    paddingBottom: 128,
  },
  contacts: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    overscrollBehavior: 'none',
    paddingTop: 8,
    paddingBottom: 64,
  },
  contact: {
    width: '100%',
    height: 80,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    icon: {
      borderRadius: 28,
      overflow: 'hidden',
    },
  },
  menuOption: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    margin: 16,
    gap: 8,
  },
  input: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    textWrap: 'nowrap',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    backgroundColor: 'transparent',
    paddingTop: 0,
    paddingBottom: 0,
    display: 'flex',
    height: 52,
    borderRadius: 8,
  },
  searchSurface: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    borderRadius: 8,
    overflow: 'hidden',
  },
  newContactButton: {
    height: 52,
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputBorder: {
    borderRadius: 12,
    borderWidth: 0,
  },
  largeTitle: {
    fontSize: 20,
    flexGrow: 1,
    paddingLeft: 16,
  },
  smallTitle: {
    fontSize: 20,
    textAlign: 'center',
    flexGrow: 1,
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 48,
  },
  line: {
    width: '100%',
  },
  members: {
    width: '100%',
    flexGrow: 1,
  },
  empty: {
    width: '100%',
    flexGrow: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    fontSize: 18,
    color: Colors.placeholder,
  },
  card: {
    width: '100%',
    height: 48,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    borderBottomWidth: 1,
  },
  icon: {
    backgroundColor: 'transparent',
  },
  modalArea: {
    width: 300,
    maxWidth: '95%',
  },
  modalSurface: {
    borderRadius: 8,
  },
  modalContent: {
    borderRadius: 8,
    paddingTop: 32,
    paddingBottom: 32,
    paddingLeft: 16,
    paddingRight: 16,
  },
  modal: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blur: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  modalLabel: {
    fontSize: 20,
    fontWeight: 600,
    textAlign: 'center',
    paddingBottom: 16,
  },
  modalClose: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: 'transparent',
  },
  modalDescription: {
    paddingTop: 16,
    fontWeight: 500,
    textAlign: 'center',
  },
  secretText: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  secret: {
    paddingRight: 16,
    fontSize: 20,
    fontWeight: 500,
  },
  secretIcon: {
    marginLeft: 8,
  },
  modalControls: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  modalControl: {
    borderRadius: 8,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 2,
    paddingBottom: 2,
  },
  fullSurface: {
    width: '100%',
    height: '100%',
  },
  headerLayout: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    height: 72,
    gap: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 16,
    paddingRight: 16,
    paddingLeft: 16,
  },
  contactHandle: {
    color: 'onSecondary',
    fontWeight: 'normal',
  },
  cardWithBorder: {
    width: '100%',
    height: 48,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    borderBottomWidth: 1,
  },
});
