export const en = {
  code: 'en',
  settings: 'Settings',
  contacts: 'Contacts',
  logout: 'Logout',
  confirmLogout: 'Are you sure you want to logout?',
  contactsUpdated: 'Updated contact status',
  disconnected: 'Disconnected from server',
  allDevices: 'Logout of all devices',
  ok: 'OK',
  cancel: 'Cancel',

  new: 'New',
  newMessage: 'New Message',
  topics: 'Topics',
  unsetSealing: 'Unset Sealing Key',
  newTopic: 'New Topic', 

  noContacts: 'No Contacts',
  noTopics: 'No Topics',
  noConnected: 'No Connected Contacts',
  subjectOptional: 'Subject (optional)',
  members: 'Members',
  sealedTopic: 'Sealed Topic',
  start: 'Start',

  communication: 'Communication for the Decentralized Web',
  setupProfile: 'Setup your profile',
  connectPeople: 'Connect with people',
  startConversation: 'Start a conversation',

  default: 'Default',
  dark: 'Dark',
  light: 'Light',

  operationFailed: 'Operation Failed',
  tryAgain: 'Please try again.',

  add: 'Add',
  save: 'Save',
  forget: 'Forget',
  unlock: 'Unlock',
  profile: 'Profile',
  application: 'Application',
  account: 'Account',
  name: 'Name',
  node: 'Node',
  location: 'Location',
  description: 'Description',
  timeFormat: 'Time Format',
  dateFormat: 'Date Format',
  theme: 'Theme',
  language: 'Language',
  timeUs: '12h',
  timeEu: '24h',
  dateUs: 'mm/dd',
  dateEu: 'dd/mm',
  registry: 'Visible in Registry',
  sealedTopics: 'Sealed Topics',
  changeLogin: 'Change Login',
  selectImage: 'Select',
  profileImage: 'Profile Image',
  profileDetails: 'Profile Details',
  enableSealed: 'Enabled Sealed Topics',
  password: 'Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  deleteKey: 'Type \'delete\' to remove key',
  delete: 'delete',
  remove: 'Delete',
  username: 'Username',
  updateProfile: 'Update Profile',

  syncError: 'Sync Error',
  callTip: 'Call Contact',
  messageTip: 'Message Contact',
  connectedTip: 'Connected Contact',
  requestedTip: 'Connection Requested by Contact',
  connectingTip: 'Connection Requested',
  pendingTip: 'Connection Requested by Unknown Contact',
  confirmedTip: 'Disconnected Contact',
  unsavedTip: 'Unknown Contact',

  actions: 'Actions',
  resync: 'Resync',
  connect: 'Connect',
  disconnect: 'Disconnect',
  disconnectContact: 'Disconnect Contact',
  deleteContact: 'Delete Contact',
  saveContact: 'Save Contact',
  saveAccept: 'Save and Accept Connection',
  saveRequest: 'Save and Request Connection',
  ignoreRequest: 'Ignore Request',
  acceptConnection: 'Accept Connection',
  requestConnection: 'Request Connection',
  cancelRequest: 'Cancel Request',
  resyncContact: 'Resync Contact',

  login: 'Login',
  create: 'Create',
  createAccount: 'Create Account',
  accountLogin: 'Account Login',
  toCreate: 'Accounts are created through a link generated from the admin dashboard.',
  admin: 'Admin',  
  loginError: 'Login Error',
  loginMessage: 'Please confirm your username and password.',
  createError: 'Create Account Error',
  createMessage: 'Please check with your administrator.',
  adminError: 'Admin Access Error',
  adminMessage: 'Please confirm your password.',

  confirmDelete: 'Deleting Account',
  areSure: 'Are you sure you want to delete the account?',

  mb: 'MB',
  gb: 'GB',
  copied: 'Copied',
  accounts: 'Accounts',
  accessAccount: 'Access Account',
  browserLink: 'Browser Link',
  mobileToken: 'Mobile Token',
  createLink: 'Create Account Link',
  configureServer: 'Configure Server',
  reloadAccounts: 'Reload Accounts',
  disableAccount: 'Disable Account',
  enableAccount: 'Enable Account',
  deleteAccount: 'Delete Account',
  hostHint: 'domain:port/app',
  federatedHost: 'Federated Host',
  storageLimit: 'Storage Limit (GB) / Account',
  storageHint: '0 for Unlimited',
  keyType: 'Account Key Type',
  accountCreation: 'Public Account Creation',
  enablePush: 'Enable Push Notifications',
  allowUnsealed: 'Allow Unsealed Topics',
  topicContent: 'Topic Content:',
  enableImage: 'Enable Image Queue',
  imageHint: 'Allow images to be posted in topics',
  enableAudio: 'Enable Audio Queue',
  audioHint: 'Allow audio to be posted in topics',
  enableVideo: 'Enable Video Queue',
  videoHint: 'Allow video to be posted in topics',
  enableWeb: 'Enable WebRTC Calls',
  webHint: 'Enable audio and video calls to contacts',
  serverUrl: 'WebRTC Server URL',
  urlHint: 'turn:ip:port?transport=udp',
  webUsername: 'WebRTC Username',
  webPassword: 'WebRTC Password',
  failedLoad: 'Failed to Load',
  limit: 'Limit',

  deleteMessage: 'Deleting Message',
  messageHint: 'Are you sure you want to delete the message?',
  attachImage: 'Attach Image',
  attachVideo: 'Attach Video',
  attachAudio: 'Attach Audio',
  attachFile: 'Attach File',
  fontColor: 'Change Font Color',
  fontSize: 'Change Font Size',
  postMessage: 'Post Message',

  close: 'Close',
  leave: 'Leave',
  confirmTopic: 'Deleting Topic',
  sureTopic: 'Are you sure you want to delete this topic?',
  confirmLeave: 'Leaving Topic',
  sureLeave: 'Are you sure you want to leave this topic?',

  details: 'Details',
  host: 'Host',
  guest: 'Guest',
  editSubject: 'Edit Subject',
  editMembership: 'Edit Membership', 
  deleteTopic: 'Delete Topic',
  leaveTopic: 'Leave Topic',

  integrated: 'Integrated',
  microphone: 'Microphone',
  camera: 'Camera'
};

export const fr = {
  code: 'fr',
  settings: 'Paramètres',
  contacts: 'Contacts',
  logout: 'Déconnexion',
  confirmLogout: 'Êtes-vous sûr de vouloir vous déconnecter?',
  contactsUpdated: 'Vos contacts ont changer',
  disconnected: 'Déconnecté du serveur',
  allDevices: 'Déconnexion de tous les appareils',
  ok: 'OK',
  cancel: 'Annuler',

  new: 'Nouveau',
  newMessage: 'Nouveau Message',
  topics: 'Sujets',
  unsetSealing: 'Clé de sécurité non définie',
  newTopic: 'Nouveau Sujet',

  noContacts: 'Pas de Contacts',
  noTopics: 'Pas de Sujets',
  noConnected: 'Pas de Contacts Connecter',
  subjectOptional: 'Sujet (optionnel)',
  members: 'Membres',
  sealedTopic: 'Sujet Sécurisé',
  start: 'Commencer',

  communication: 'Communication pour le Web Décentralisé',
  setupProfile: 'Configurez votre profil',
  connectPeople: 'Connectez avec les gens',
  startConversation: 'Commencez une conversation',

  default: 'Défaut',
  dark: 'Sombre',
  light: 'Lumineux',

  operationFailed: 'Opération Échouée',
  tryAgain: 'Veuillez réessayer.',

  add: 'Ajouter',
  save: 'Enregistrer',
  forget: 'Oublier',
  unlock: 'Déverrouiller',
  profile: 'Profil',
  application: 'Application',
  account: 'Compte',
  name: 'Nom',
  node: 'Serveur',
  location: 'Emplacement',
  description: 'Description',
  timeFormat: 'Format de l\'heure',
  dateFormat: 'Format de la date',
  theme: 'Thème',
  language: 'Langue',
  timeUs: '12h',
  timeEu: '24h',
  dateUs: 'mm/jj',
  dateEu: 'jj/mm',
  registry: 'Visible dans le Registre',
  sealedTopics: 'Sujets Sécurisé',
  changeLogin: 'Changer Identifiants',
  selectImage: 'Sélectionner',
  profileImage: 'Image de Profil',
  profileDetails: 'Détails du Profil',
  enableSealed: 'Activer les Sujets Sécurisé',
  password: 'Mot de Passe',
  newPassword: 'Nouveau Mot de Passe',
  confirmPassword: 'Confirmer le Mot de Passe',
  deleteKey: 'Tapez \'supprimer\' pour supprimer la clé',
  delete: 'supprimer',
  remove: 'Supprimer',
  username: 'Nom d\'Utilisateur',
  updateProfile: 'Mettre à Jour le Profil',

  syncError: 'Erreur de Synchronisation',
  callTip: 'Appeler le Contact',
  messageTip: 'Envoyer un Message au Contact',
  connectedTip: 'Contact Connecté',
  requestedTip: 'Demande de Connexion Envoyée par le Contact',
  connectingTip: 'Demande de Connexion en Cours',
  pendingTip: 'Demande de Connexion Envoyée par un Contact Inconnu',
  confirmedTip: 'Contact Déconnecté',
  unsavedTip: 'Contact Inconnu',

  actions: 'Actions',
  resync: 'Resynchroniser',
  connect: 'Connecter',
  disconnect: 'Déconnecter',
  disconnectContact: 'Déconnecter le Contact',
  deleteContact: 'Supprimer le Contact',
  saveContact: 'Enregistrer le Contact',
  saveAccept: 'Enregistrer et Accepter la Connexion',
  saveRequest: 'Enregistrer et Demander la Connexion',
  ignoreRequest: 'Ignorer la Demande',
  acceptConnection: 'Accepter la Connexion',
  requestConnection: 'Demander une Connexion',
  cancelRequest: 'Annuler la Demande',
  resyncContact: 'Resynchroniser le Contact',

  login: 'Connecter',
  create: 'Créer',
  createAccount: 'Créer un Compte',
  accountLogin: 'Connexion au Compte',
  toCreate: 'Les comptes sont créés via un lien généré depuis le tableau de bord d\'administration.',
  admin: 'Administrateur',
  loginError: 'Erreur de connexion',
  loginMessage: 'Veuillez confirmer votre nom d\'utilisateur et votre mot de passe.',
  createError: 'Erreur de création de compte',
  createMessage: 'Veuillez vérifier auprès de votre administrateur.',
  adminError: 'Erreur d\'Accès',
  adminMessage: 'Veuillez confirmer votre mot de passe',

  confirmDelete: 'Suppression de Compte',
  areSure: 'Êtes-vous sûr de vouloir supprimer le compte?',

  mb: 'Mo',
  gb: 'Go',
  copied: 'Copié',
  accounts: 'Comptes',
  accessAccount: 'Accéder au Compte',
  browserLink: 'Lien du Navigateur',
  mobileToken: 'Code Mobile',
  createLink: 'Lien pour Créer un Compte',
  configureServer: 'Configurer le Serveur',
  reloadAccounts: 'Recharger les Comptes',
  disableAccount: 'Désactiver le Compte',
  enableAccount: 'Activer le Compte',
  deleteAccount: 'Supprimer le Compte',
  hostHint: 'domaine:port/app',
  federatedHost: 'Hôte Fédéré',
  storageLimit: 'Limite de Espace (Go) / Compte',
  storageHint: '0 pour Illimité',
  keyType: 'Type de Clé',
  accountCreation: 'Création de Compte Public',
  enablePush: 'Activer les Notifications Push',
  allowUnsealed: 'Autoriser les Sujets non Sécurisés',
  topicContent: 'Contenu du Sujet:',
  enableImage: 'Activer les Images du Sujet',
  imageHint: 'Autoriser la publication d\'images dans des sujets',
  enableAudio: 'Activer l\'Audio du Suject',
  audioHint: 'Autoriser la publication d\'audio dans des sujets',
  enableVideo: 'Activer les Videos du Sujet',
  videoHint: 'Autoriser la publication de video dans des sujets',
  enableWeb: 'Activer les Appels WebRTC',
  webHint: 'Autoriser les appels audio et vidéo aux contacts',
  serverUrl: 'URL du Serveur WebRTC',
  urlHint: 'turn:ip:port?transport=udp',
  webUsername: 'Nom d\'Utilisateur WebRTC',
  webPassword: 'Mot de Passe WebRTC',
  failedLoad: 'Échec du Chargement',
  limit: 'Limite',

  deleteMessage: 'Suppression du Message',
  messageHint: 'Êtes-vous Sûr de Vouloir Supprimer le Message?',
  attachImage: 'Joindre une Image',
  attachVideo: 'Joindre une Vidéo',
  attachAudio: 'Joindre un Audio',
  attachFile: 'Joindre un Fichier',
  fontColor: 'Changer la Couleur du Text',
  fontSize: 'Changer la Taille du Text',
  postMessage: 'Publier le Message',

  close: 'Fermer',
  leave: 'Quitter',
  confirmTopic: 'Suppression du Sujet',
  sureTopic: 'Êtes-Vous Sûr de Vouloir Supprimer ce Sujet?',
  confirmLeave: 'Quitter le Suject',
  sureLeave: 'Êtes-Vous Sûr de Vouloir Quitter ce Sujet?',

  details: 'Détails',
  host: 'Hôte',
  guest: 'Invité',
  editSubject: 'Modifier le Sujet',
  editMembership: 'Modifier Membres du Suject',
  deleteTopic: 'Supprimer le Sujet',
  leaveTopic: 'Quitter le Suject',

  integrated: 'Intégré',
  microphone: 'Microphone',
  camera: 'Caméra'
};

