export const en = {
  code: 'en',
  settings: 'Settings',
  contacts: 'Contacts',
  logout: 'Logout',
  confirmLogout: 'Are you sure you want to logout?',
  contactsUpdated: 'Updated contact status',
  disconnected: 'Disconnected from server',
  allDevices: 'Logout of all devices',
  ok: 'OK',
  cancel: 'Cancel',

  new: 'New',
  newMessage: 'New Message',
  topics: 'Topics',
  unsetSealing: 'Unset Sealing Key',
  newTopic: 'New Topic', 

  noTopics: 'No Topics',
  noConnected: 'No Connected Contacts',
  subjectOptional: 'Subject (optional)',
  members: 'Members',
  sealedTopic: 'Sealed Topic',
  start: 'Start',

  communication: 'Communication for the Decentralized Web',
  setupProfile: 'Setup your profile',
  connectPeople: 'Connect with people',
  startConversation: 'Start a conversation',

  default: 'Default',
  dark: 'Dark',
  light: 'Light',

  operationFailed: 'Operation Failed',
  tryAgain: 'Please try again.',

  add: 'Add',
  save: 'Save',
  forget: 'Forget',
  unlock: 'Unlock',
  profile: 'Profile',
  application: 'Application',
  account: 'Account',
  name: 'Name',
  node: 'Node',
  location: 'Location',
  description: 'Description',
  timeFormat: 'Time Format',
  dateFormat: 'Date Format',
  theme: 'Theme',
  language: 'Language',
  timeUs: '12h',
  timeEu: '24h',
  dateUs: 'mm/dd',
  dateEu: 'dd/mm',
  registry: 'Visible in Registry',
  sealedTopics: 'Sealed Topics',
  changeLogin: 'Change Login',
  selectImage: 'Select',
  profileImage: 'Profile Image',
  profileDetails: 'Profile Details',
  enableSealed: 'Enabled Sealed Topics',
  password: 'Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  deleteKey: 'Type \'delete\' to remove key',
  delete: 'delete',
  remove: 'Delete',
  username: 'Username',
  updateProfile: 'Update Profile',

  syncError: 'Sync Error',
  callTip: 'Call Contact',
  messageTip: 'Message Contact',
  connectedTip: 'Connected Contact',
  requestedTip: 'Connection Requested by Contact',
  connectingTip: 'Connection Requested',
  pendingTip: 'Connection Requested by Unknown Contact',
  confirmedTip: 'Disconnected Contact',
  unsavedTip: 'Unknown Contact',

  actions: 'Actions',
  resync: 'Resync',
  connect: 'Connect',
  disconnect: 'Disconnect',
  disconnectContact: 'Disconnect Contact',
  deleteContact: 'Delete Contact',
  saveContact: 'Save Contact',
  saveAccept: 'Save and Accept Connection',
  saveRequest: 'Save and Request Connection',
  ignoreRequest: 'Ignore Request',
  acceptConnection: 'Accept Connection',
  requestConnection: 'Request Connection',
  cancelRequest: 'Cancel Request',
  resyncContact: 'Resync Contact',

  login: 'Login',
  create: 'Create',
  createAccount: 'Create Account',
  accountLogin: 'Account Login',
  toCreate: 'Accounts are created through a link generated from the admin dashboard.',
  admin: 'Admin',  
  loginError: 'Login Error',
  loginMessage: 'Please confirm your username and password.',
  createError: 'Create Account Error',
  createMessage: 'Please check with your administrator.',
  adminError: 'Admin Access Error',
  adminMessage: 'Please confirm your password.',
};

export const fr = {
  code: 'fr',
  settings: 'Paramètres',
  contacts: 'Contacts',
  logout: 'Déconnexion',
  confirmLogout: 'Êtes-vous sûr de vouloir vous déconnecter?',
  contactsUpdated: 'Vos contacts ont changer',
  disconnected: 'Déconnecté du serveur',
  allDevices: 'Déconnexion de tous les appareils',
  ok: 'OK',
  cancel: 'Annuler',

  new: 'Nouveau',
  newMessage: 'Nouveau Message',
  topics: 'Sujets',
  unsetSealing: 'Clé de sécurité non définie',
  newTopic: 'Nouveau Sujet',

  noTopics: 'Pas de Sujets',
  noConnected: 'Pas de Contacts Connecter',
  subjectOptional: 'Sujet (optionnel)',
  members: 'Membres',
  sealedTopic: 'Sujet Sécurisé',
  start: 'Commencer',

  communication: 'Communication pour le Web Décentralisé',
  setupProfile: 'Configurez votre profil',
  connectPeople: 'Connectez avec les gens',
  startConversation: 'Commencez une conversation',

  default: 'Défaut',
  dark: 'Sombre',
  light: 'Lumineux',

  operationFailed: 'Opération Échouée',
  tryAgain: 'Veuillez réessayer.',

  add: 'Ajouter',
  save: 'Enregistrer',
  forget: 'Oublier',
  unlock: 'Déverrouiller',
  profile: 'Profil',
  application: 'Application',
  account: 'Compte',
  name: 'Nom',
  node: 'Serveur',
  location: 'Emplacement',
  description: 'Description',
  timeFormat: 'Format de l\'heure',
  dateFormat: 'Format de la date',
  theme: 'Thème',
  language: 'Langue',
  timeUs: '12h',
  timeEu: '24h',
  dateUs: 'mm/jj',
  dateEu: 'jj/mm',
  registry: 'Visible dans le Registre',
  sealedTopics: 'Sujets Sécurisé',
  changeLogin: 'Changer Identifiants',
  selectImage: 'Sélectionner',
  profileImage: 'Image de Profil',
  profileDetails: 'Détails du Profil',
  enableSealed: 'Activer les Sujets Sécurisé',
  password: 'Mot de Passe',
  newPassword: 'Nouveau Mot de Passe',
  confirmPassword: 'Confirmer le Mot de Passe',
  deleteKey: 'Tapez \'supprimer\' pour supprimer la clé',
  delete: 'supprimer',
  remove: 'Supprimer',
  username: 'Nom d\'Utilisateur',
  updateProfile: 'Mettre à Jour le Profil',

  syncError: 'Erreur de Synchronisation',
  callTip: 'Appeler le Contact',
  messageTip: 'Envoyer un Message au Contact',
  connectedTip: 'Contact Connecté',
  requestedTip: 'Demande de Connexion Envoyée par le Contact',
  connectingTip: 'Demande de Connexion en Cours',
  pendingTip: 'Demande de Connexion Envoyée par un Contact Inconnu',
  confirmedTip: 'Contact Déconnecté',
  unsavedTip: 'Contact Inconnu',

  actions: 'Actions',
  resync: 'Resynchroniser',
  connect: 'Connecter',
  disconnect: 'Déconnecter',
  disconnectContact: 'Déconnecter le Contact',
  deleteContact: 'Supprimer le Contact',
  saveContact: 'Enregistrer le Contact',
  saveAccept: 'Enregistrer et Accepter la Connexion',
  saveRequest: 'Enregistrer et Demander la Connexion',
  ignoreRequest: 'Ignorer la Demande',
  acceptConnection: 'Accepter la Connexion',
  requestConnection: 'Demander une Connexion',
  cancelRequest: 'Annuler la Demande',
  resyncContact: 'Resynchroniser le Contact',

  login: 'Connecter',
  create: 'Créer',
  createAccount: 'Créer un Compte',
  accountLogin: 'Connexion au Compte',
  toCreate: 'Les comptes sont créés via un lien généré depuis le tableau de bord d\'administration.',
  admin: 'Administrateur',
  loginError: 'Erreur de connexion',
  loginMessage: 'Veuillez confirmer votre nom d\'utilisateur et votre mot de passe.',
  createError: 'Erreur de création de compte',
  createMessage: 'Veuillez vérifier auprès de votre administrateur.',
  adminError: 'Erreur d\'Accès',
  adminMessage: 'Veuillez confirmer votre mot de passe',
};

