import {StyleSheet} from 'react-native';
import {Colors} from '../constants/Colors';

export const styles = StyleSheet.create({
  profile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    paddingBottom: 32,
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    paddingLeft: 16,
    paddingRight: 16,
  },
  header: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 8,
    paddingLeft: 8,
    width: '100%',
    zIndex: 1,
  },
  headerLabel: {
    flexShrink: 1,
    fontSize: 22,
    textAlign: 'center',
    textWrap: 'nowrap',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    paddingTop: 8,
    paddingLeft: 16,
    paddingRight: 16,
    flexGrow: 1,
    verticalAlign: 'baseline',
    lineHeight: 22,
  },
  spaceHolder: {
    width: 64,
  },
  back: {
    flexShrink: 0,
    marginRight: 0,
    marginLeft: 0,
    backgroundColor: 'transparent',
  },
  image: {
    position: 'relative',
    width: '90%',
    maxWidth: 250,
    marginTop: 16,
    marginBottom: 8,
  },
  logo: {
    aspectRatio: 1,
    resizeMode: 'contain',
    borderRadius: 8,
    width: null,
    height: null,
    borderWidth: 1,
  },
  line: {
    marginTop: 16,
    marginBottom: 16,
    height: 2,
    width: '100%',
  },
  attributes: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    width: '100%',
    paddingTop: 12,
  },
  attribute: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 32,
    paddingRight: 32,
  },
  icon: {
    flexShrink: 0,
    width: 32,
    display: 'flex',
    justifyContent: 'flex-begin',
    height: '100%',
    backgroundColor: 'transparent',
  },
  label: {
    fontSize: 16,
  },
  labelUnset: {
    fontSize: 16,
    fontStyle: 'italic',
    flexGrow: 1,
  },
  labelSet: {
    fontSize: 16,
    flexGrow: 1,
  },
  nameSet: {
    fontSize: 24,
    width: '100%',
    paddingLeft: 32,
    paddingRight: 72,
  },
  nameUnset: {
    fontSize: 24,
    width: '100%',
    paddingLeft: 32,
    paddingRight: 32,
    fontStyle: 'italic',
  },
  status: {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unknownStatus: {
    color: Colors.unsaved,
    fontSize: 14,
  },
  savedStatus: {
    color: Colors.confirmed,
    fontSize: 14,
  },
  pendingStatus: {
    color: Colors.pending,
    fontSize: 14,
  },
  requestedStatus: {
    color: Colors.requested,
    fontSize: 14,
  },
  connectingStatus: {
    color: Colors.connecting,
    fontSize: 14,
  },
  connectedStatus: {
    color: Colors.connected,
    fontSize: 14,
  },
  offsyncStatus: {
    color: Colors.offsync,
    fontSize: 14,
  },
  modal: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
  blur: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  content: {
    display: 'flex',
    justifyContent: 'center',
    height: '100%',
    gap: 8,
  },
  close: {
    paddingTop: 8,
  },
  surface: {
    padding: 16,
  },
  actions: {
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    paddingTop: 16,
  },
  action: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },  
  actionLabel: {
    fontSize: 12,
  },
  actionIcon: {
    position: 'relative',
    top: 8,
    backgroundColor: 'transparent',
    padding: 0,
    margin: 0,
  },
});
