import {StyleSheet} from 'react-native';
import { Colors } from '../constants/Colors';

export const styles = StyleSheet.create({
  setup: {
    position: 'relative',
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    minWidth: 0,
  },
  title: {
    fontSize: 20,
    textAlign: 'center',
    flexGrow: 1,
    minWidth: 0,
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 48,
    paddingLeft: 8,
    paddingRight: 8,
  },
  line: {
    width: '100%',
  },
  divider: {
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  form: {
    width: '100%',
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    height: 100,
    minWidth: 0,
    position: 'relative',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    paddingTop: 16,
    minWidth: 0,
  },
  busy: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: '100%',
  },
  option: {
    width: '100%',
    height: 32,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 6,
    paddingLeft: 16,
    paddingRight: 16,
    minWidth: 0,
  },
  label: {
    fontSize: 14,
    flexShrink: 1,
    minWidth: 0,
  },
  inputSurface: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    marginRight: 8,
    marginLeft: 8,
    display: 'flex',
    borderRadius: 8,
  },
  input: {
    flexGrow: 1,
    backgroundColor: 'transparent',
    paddingTop: 0,
    paddingBottom: 0,
    display: 'flex',
    height: 32,
    maxHeight: 32,
    borderRadius: 8,
    minWidth: 0,
    flexShrink: 1,
    fontSize: 14,
  },
  inputUnderline: {
    display: 'none',
  },
  radioSelect: {
    display: 'flex',
    flexDirection: 'row',
    paddingLeft: 50,
    height: 32,
    gap: 24,
  },
  radio: {
    padding: 0,
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 72,
  },
  radioLabel: {
    fontSize: 12,
    position: 'absolute',
    left: -36,
    fontWeight: 'bold',
  },
  controlSwitch: {
    transform: [{scaleX: 0.7}, {scaleY: 0.7}],
  },
});
