import { StyleSheet } from 'react-native';
import { Colors } from 'constants/Colors';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    paddingBottom: 32,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 32,
  },
  icon: {
    paddingTop: 2,
  },
  warn: {
    paddingTop: 2,
    paddingRight: 8,
  },
  wrapper: {
    backgroundColor: Colors.formBackground,
  },
  drawer: {
    paddingTop: 16,
  },
  action: {
    width: 64,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    fontSize: 18,
    overflow: 'hidden',
    flexGrow: 1,
    textAlign: 'center',
  }, 
  title: {
    display: 'flex',
    flexDirection: 'row',
    flexGrow: 1,
    flex: 1,
    width: '100%',
    textAlign: 'start',
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    paddingTop: 16,
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  headerText: {
    paddingLeft: 16,
    fontSize: 14,
    paddingRight: 8,
    color: Colors.text,
  },
  camera: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    padding: 8,
    backgroundColor: Colors.lightgrey,
    borderBottomLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  gallery: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    padding: 8,
    backgroundColor: Colors.lightgrey,
    borderBottomRightRadius: 8,
    borderTopLeftRadius: 8,
  },
  alert: {
    height: 32,
  },
  detail: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    color: Colors.text,
    paddingLeft: 32,
    paddingRight: 32,
  },
  attribute: {
    display: 'flex',
    flexDirection: 'row',
    paddingBottom: 8,
  },
  nonametext: {
    fontSize: 18,
    paddingRight: 8,
    fontWeight: 'bold',
    color: Colors.grey,
  },
  nametext: {
    fontSize: 18,
    paddingRight: 8,
    fontWeight: 'bold',
  },
  locationtext: {
    fontSize: 16,
    paddingLeft: 8,
    color: Colors.text,
  },
  nolocationtext: {
    fontSize: 16,
    paddingLeft: 8,
    color: Colors.grey,
  },
  descriptiontext: {
    fontSize: 16,
    paddingLeft: 8,
    color: Colors.text,
  },
  nodescriptiontext: {
    fontSize: 16,
    paddingLeft: 8,
    color: Colors.grey,
  },
  notify: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 16,
  },
  notifyText: {
    fontSize: 16,
    color: Colors.text,
  },
  sealUpdate: {
    position: 'absolute',
    top: 0,
    height: '100%',
    left: 0,
    width: '100%',
  },
  sealable: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 8,
  },
  sealableText: {
    fontSize: 16,
    color: Colors.text,
  },
  sealableSwitch: {
    transform: [{ scaleX: .7 }, { scaleY: .7 }],
  },
  visible: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 16,
  },
  visibleText: {
    fontSize: 16,
    color: Colors.text,
  },
  visibleSwitch: {
    transform: [{ scaleX: .7 }, { scaleY: .7 }],
  },
  logout: {
    marginTop: 32,
    borderRadius: 4,
    backgroundColor: Colors.primary,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 8,
    paddingBottom: 8,
  },
  logoutText: {
    color: Colors.white,
    paddingLeft: 8,
  },
  unconfirmed: {
    backgroundColor: Colors.lightgrey,
    borderRadius: 4,
    padding: 8,
    width: 72,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  remove: {
    backgroundColor: Colors.error,
    borderRadius: 4,
    padding: 8,
    width: 72,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeText: {
    color: Colors.white,
  },
  switch: {
    false: Colors.grey,
    true: Colors.background,
  },
  editWrapper: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.8)'
  },
  editContainer: {
    backgroundColor: Colors.formBackground,
    padding: 16,
    width: '80%',
    maxWidth: 400,
  },
  editHeader: {
    fontSize: 18,
    paddingBottom: 16,
  },
  editList: {
    width: '100%',
    borderWidth: 1,
    borderColor: Colors.lightgrey,
    borderRadius: 2,
  },
  inputField: {
    width: '100%',
    borderWidth: 1,
    borderColor: Colors.lightgrey,
    borderRadius: 4,
    padding: 8,
    marginBottom: 8,
    maxHeight: 92,
    display: 'flex',
    flexDirection: 'row',
  },
  input: {
    fontSize: 14,
    flexGrow: 1,
  },
  editControls: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  close: {
    borderWidth: 1,
    borderColor: Colors.lightgrey,
    borderRadius: 4,
    padding: 8,
    marginTop: 8,
    width: 72,
    display: 'flex',
    alignItems: 'center',
  },
  cancel: {
    borderWidth: 1,
    borderColor: Colors.lightgrey,
    borderRadius: 4,
    padding: 8,
    marginRight: 8,
    width: 72,
    display: 'flex',
    alignItems: 'center',
  },
  disabled: {
    borderWidth: 1,
    borderColor: Colors.lightgrey,
    padding: 8,
    borderRadius: 4,
    width: 72,
    display: 'flex',
    alignItems: 'center',
  },
  disabledText: {
    color: Colors.disabled,
  },
  save: {
    padding: 8,
    borderRadius: 4,
    backgroundColor: Colors.primary,
    width: 72,
    display: 'flex',
    alignItems: 'center',
  },
  save: {
    padding: 8,
    borderRadius: 4,
    backgroundColor: Colors.primary,
    width: 72,
    display: 'flex',
    alignItems: 'center',
  },
  link: {
    marginTop: 16,
    display: 'flex',
    flexDirection: 'row',
  },
  linkText: {
    paddingLeft: 8,
    color: Colors.primary,
  },
  delete: {
    backgroundColor: Colors.error,
    marginTop: 16,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 4,
  }, 
  deleteText: {
    paddingLeft: 8,
    color: Colors.white,
  },
  saveText: {
    color: Colors.white,
  },
  disconnected: {
    color: Colors.alert,
  },
})

