name: databag-example-ssl

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # Edit the Caddyfile and replace "example.com" with your own domain
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Recommended by Caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
  app:
    image: balzack/databag:latest
    restart: unless-stopped
    volumes:
      - database:/var/lib/databag
    environment:
      - ADMIN=password
      - DATABAG_PORT=443
volumes:
  database:
  caddy_data:
  caddy_config:
