import { NativeModules, Platform } from 'react-native'

const Strings = [
  {
    visibleRegistry: 'Visible in Registry',
    edit: 'Edit',
    enableNotifications: 'Push Notifications',
    sealedTopics: 'Sealed Topics',
    colorMode: 'Color Mode',
    hourMode: 'Hour',
    dateMode: 'Date',
    language: 'Language',
    logout: 'Logout',
    changeLogin: 'Change Login',
    deleteAccount: 'Delete Account',
    contacts: 'Contacts',
    topics: 'Topics',
    messages: 'Messages',
    support: 'Support',
    blocked: 'Blocked',
    account: 'Account',
    display: 'Format',
    messaging: 'Messaging',
    timeFull: '24h',
    timeHalf: '12h',
    monthStart: 'mm/dd',
    monthEnd: 'dd/mm',

    sealUnset: 'Generate a key to enable end-to-end encrypted topics.',
    sealUnlocked: 'Disabling the sealing key will block access to all end-to-end encrypted topics from this device until the key is unlocked again.',
    sealLocked: 'Unlock the sealing key to support end-to-end encrypted topics on this device.',
    sealDelete: 'Deleting the sealing key will premanently remove access to any existing end-to-end encrypted topics for ALL of your devices.',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    generate: 'Generate',
    disable: 'Disable',
    delete: 'Delete',
    unlock: 'Unlock',
    removeSeal: 'Remove Sealing Key',
    disableSeal: 'Disable Sealing Key',
    unlockSeal: 'Unlock Sealing Key',
    typeDelete: 'Type [delete] to remove key',
    deleteKey: 'delete',
    enableTopics: 'Enable Sealed Topics',
    manageTopics: 'Manage Sealing Key',
    changePassword: 'Change sealing key password.',
    update: 'Update',
    changeKey: 'Change Key Password',
    delayMessage: 'Key generation can take several minutes.',
  },
  {
    visibleRegistry: 'Visible dans le Registre',
    edit: 'Modifier',
    enableNotifications: 'Notifications Push',
    sealedTopics: 'Sujets Sécurisés',
    colorMode: 'Mode de Couleur',
    hourMode: 'Heure',
    dateMode: 'Date',
    language: 'Langue',
    logout: 'Se Déconnecter',
    changeLogin: 'Changer le Mot de Passe',
    deleteAccount: 'Supprimer le Compte',
    contacts: 'Contacts',
    topics: 'Sujets',
    messages: 'Messages',
    support: 'Aide',
    blocked: 'Bloqués',
    account: 'Compte',
    display: 'Format',
    messaging: 'Messagerie',
    timeFull: '24h',
    timeHalf: '12h',
    monthStart: 'mm/jj',
    monthEnd: 'jj/mm',

    sealUnset: 'Générez une clé pour activer les sujets chiffrés de bout en bout.',
    sealUnlocked: 'La désactivation de la clé de scellement supprimera l\'accès à tous les sujets chiffrés de bout en bout jusqu\'à ce que la clé soit à nouveau déverrouillée.',
    sealLocked: 'Déverrouillez la clé de scellement pour activer les sujets chiffrés de bout en bout sur cet appareil.',
    sealDelete: 'La suppression de la clé de scellement supprimera définitivement l’accès à tous les sujets cryptés de bout en bout existants pour TOUS vos appareils.',
    password: 'Mot de passe',
    confirmPassword: 'Confirmez le mot de passe',
    generate: 'Générer',
    disable: 'Désactiver',
    delete: 'Supprimer',
    unlock: 'Activer',
    removeSeal: 'Supprimer la clé de sécurité',
    disableSeal: 'Désactiver la clé de sécurité',
    unlockSeal: 'Déverrouiller la clé de sécurité',
    typeDelete: 'Tapez [supprimer] pour supprimer la clé',
    deleteKey: 'supprimer',
    enableTopics: 'Activer les sujets sécurisés',
    manageTopics: 'Gérer la clé de sécurité',
    changePassword: 'Changez le mot de passe de la clé de sécurité.',
    update: 'Mise à jour',
    changeKey: 'Changer le mot de passe clé',
    delayMessage: 'La génération de clé peut prendre plusieurs minutes.',
  },
  {
    visibleRegistry: 'Visible en el Registro',
    edit: 'Editar',
    enableNotifications: 'Notificaciones Push',
    sealedTopics: 'Temas Protegidos',
    colorMode: 'Modo de Color',
    hourMode: 'Hora',
    dateMode: 'Fecha',
    language: 'Idioma',
    logout: 'Cerrar Sesión',
    changeLogin: 'Cambiar la contraseña',
    deleteAccount: 'Borrar Cuenta',
    contacts: 'Contactos',
    topics: 'Temas',
    messages: 'Mensajes',
    support: 'Ayuda',
    blocked: 'Oculto',
    account: 'Cuenta',
    display: 'Formato',
    messaging: 'Mensajería',
    timeFull: '24h',
    timeHalf: '12h',
    monthStart: 'mm/dd',
    monthEnd: 'dd/mm',

    sealUnset: 'Genere una clave para habilitar temas cifrados de un extremo a otro.',
    sealUnlocked: 'Al desactivar la clave de sellado se eliminará el acceso a todos los temas cifrados de extremo a extremo hasta que la clave se desbloquee nuevamente.',
    sealLocked: 'Desbloquee la clave de sellado para habilitar temas cifrados de extremo a extremo en este dispositivo.',
    sealDelete: 'Al eliminar la clave de sellado, se eliminará de forma permanente el acceso a cualquier tema cifrado de extremo a extremo existente para TODOS sus dispositivos.',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    generate: 'Generar',
    disable: 'Desactivar',
    delete: 'Borrar',
    unlock: 'Desbloquear',
    removeSeal: 'Borrar clave de seguridad',
    disableSeal: 'Desactivar clave de seguridad',
    unlockSeal: 'Desbloquear clave de seguridad',
    typeDelete: 'Escriba [borrar] para borrar la clave',
    deleteKey: 'borrar',
    enableTopics: 'Habilitar temas seguros',
    manageTopics: 'Administrar clave de seguridad',
    changePassword: 'Cambiar la contraseña de la clave de seguridad.',
    update: 'Actualizar',
    changeKey: 'Cambiar clave Contraseña',
    delayMessage: 'La generación de claves puede tardar varios minutos.',
  },
  {
    visibleRegistry: 'Sichtbar in der Registrierung',
    edit: 'Bearbeiten',
    enableNotifications: 'Mitteilungen',
    sealedTopics: 'Gesicherte Themen',
    colorMode: 'Farmodus',
    hourMode: 'Stunde',
    dateMode: 'Datum',
    language: 'Sprache',
    logout: 'Ausloggen',
    changeLogin: 'Kennwort Aktualisieren',
    deleteAccount: 'Konto Löschen',
    contacts: 'Kontakte',
    topics: 'Themen',
    messages: 'Mitteilungen',
    support: 'Helfen',
    blocked: 'Versteckt',
    account: 'Konto',
    display: 'Format',
    messages: 'Nachrichtenübermittlung',
    timeFull: '24h',
    timeHalf: '12h',
    monthStart: 'mm/dd',
    monthEnd: 'dd/mm',

    sealUnset: 'Generieren Sie einen Schlüssel, um Ende-zu-Ende-verschlüsselte Themen zu ermöglichen.',
    sealUnlocked: 'Durch das Deaktivieren des Versiegelungsschlüssels wird der Zugriff auf alle Ende-zu-Ende-verschlüsselten Themen entfernt, bis der Schlüssel wieder entsperrt wird.',
    sealLocked: 'Entsperren Sie den Versiegelungsschlüssel, um Ende-zu-Ende-verschlüsselte Themen auf diesem Gerät zu aktivieren.',
    sealDelete: 'Durch das Löschen des Siegelschlüssels wird der Zugriff auf alle vorhandenen Ende-zu-Ende-verschlüsselten Themen für ALLE Ihre Geräte dauerhaft entfernt.',
    password: 'Passwort',
    confirmPassword: 'Bestätige das Passwort',
    generate: 'Generieren',
    disable: 'Deaktivieren',
    delete: 'Löschen',
    unlock: 'Freischalten',
    removeSeal: 'Sicherheitsschlüssel entfernen',
    disableSeal: 'Sicherheitsschlüssel deaktivieren',
    unlockSeal: 'Sicherheitsschlüssel entsperren',
    typeDelete: 'Geben Sie [löschen], um den Schlüssel zu entfernen',
    deleteKey: 'löschen',
    enableTopics: 'Aktivieren Sie gesicherte Themen',
    manageTopics: 'Sicherheitsschlüssel verwalten',
    changePassword: 'Ändern Sie das Passwort des Sicherheitsschlüssels',
    update: 'Aktualisieren',
    changeKey: 'Schlüsselpasswort ändern',
    delayMessage: 'Die Schlüsselgenerierung kann mehrere Minuten dauern.',
  }
];

export function getLanguageStrings() {
  const locale = Platform.OS === 'ios' ? NativeModules.SettingsManager.settings.AppleLocale || NativeModules.SettingsManager.settings.AppleLanguages[0] : NativeModules.I18nManager.localeIdentifier;

  const lang = locale.slice(0, 2) || '';

  if (lang === 'en') {
    return Strings[0];
  }
  if (lang === 'fr') {
    return Strings[1];
  }
  if (lang === 'es') {
    return Strings[2];
  }
  if (lang === 'de') {
    return Strings[3];
  }
  return Strings[0];
};
