/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package databag

type NodeConfig struct {

	Domain string `json:"domain"`

	PublicLimit int64 `json:"publicLimit"`

	AccountStorage int64 `json:"accountStorage"`
}
