/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-databag/swagger-codegen.git)
 */
package databag

type Connect struct {

	RequestorcardId string `json:"requestorcardId,omitempty"`

	RequestedcardId string `json:"requestedcardId,omitempty"`

	Timestamp int32 `json:"timestamp"`

	Profile *Profile `json:"profile"`

	Token string `json:"token"`

	ContentRevision int64 `json:"contentRevision"`
}
