/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-databag/swagger-codegen.git)
 */
package databag

type Article struct {

	ArticleId string `json:"articleId"`

	ArticleRevision int64 `json:"articleRevision"`

	Type_ string `json:"type"`

	Data string `json:"data"`

	Created int32 `json:"created"`

	Modified int32 `json:"modified"`

	Status string `json:"status"`

	Labels []string `json:"labels"`

	Groups []string `json:"groups,omitempty"`

	TagCount int32 `json:"tagCount"`

	TagUpdate int32 `json:"tagUpdate,omitempty"`

	TagRevision int64 `json:"tagRevision"`
}
