/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-databag/swagger-codegen.git)
 */
package databag

type CardData struct {

	Revision int64 `json:"revision,omitempty"`

	Status string `json:"status"`

	Notes string `json:"notes,omitempty"`

	Token string `json:"token,omitempty"`

	Groups []string `json:"groups,omitempty"`
}
