/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-databag/swagger-codegen.git)
 */
package databag

type Dialogue struct {

	DialogueId string `json:"dialogueId"`

	DialogueRevison int64 `json:"dialogueRevison,omitempty"`

	Type_ string `json:"type"`

	Data string `json:"data"`

	Created int32 `json:"created"`

	Active bool `json:"active"`

	InsightRevision int64 `json:"insightRevision,omitempty"`

	Insights []DialogueInsights `json:"insights"`
}
