/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package databag

type InlineResponse2002 struct {

	BlockId string `json:"blockId,omitempty"`

	BlockRevision int64 `json:"blockRevision,omitempty"`

	Tag *Tag `json:"tag,omitempty"`
}
