/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-databag/swagger-codegen.git)
 */
package databag

type Revision struct {

	Profile int64 `json:"profile"`

	Content int64 `json:"content"`

	Label int64 `json:"label"`

	Share int64 `json:"share"`

	Card int64 `json:"card"`

	Dialogue int64 `json:"dialogue"`

	Insight int64 `json:"insight"`
}
