import { StyleSheet } from 'react-native';
import { Colors } from 'constants/Colors';

export const styles = StyleSheet.create({
  content: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.screenBase,
  },
  details: {
    position: 'relative',
    top: -32,
    minHeight: 32,
    borderTopRightRadius: 32,
    borderTopLeftRadius: 32,
    backgroundColor: Colors.screenBase,
    borderTopWidth: 1,
    borderColor: Colors.areaBorder,
    borderLeftWidth: 0.2,
    borderRightWidth: 0.2,
    paddingLeft: 1,
    paddingRight: 1,
  },
  control: {
    position: 'absolute',
    width: '100%',
    top: -24,
    display: 'flex',
    alignItems: 'center',
  },
  edit: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: Colors.screenBase,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 2,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
    borderColor: Colors.areaBorder,
  },
  editLabel: {
    color: Colors.text,
    paddingRight: 8,
    paddingTop: 2,
    fontSize: 16,
    fontFamily: 'roboto',
    color: Colors.linkText,
  },
  nameSet: {
    color: Colors.text,
    fontFamily: 'roboto',
    fontSize: 48,
    paddingTop: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  nameUnset: {
    color: Colors.inputPlaceholder,
    fontFamily: 'roboto',
    fontSize: 48,
    paddingTop: 8,
    paddingLeft: 16,
    fontStyle: 'italic',
  },
  username: {
    color: Colors.text,
    fontFamily: 'roboto',
    fontSize: 18,
    paddingLeft: 16,
    paddingBottom: 16,
  },
  group: {
    marginLeft: 16,
    marginRight: 16,
    backgroundColor: Colors.areaBase,
    borderRadius: 8,
    marginTop: 16,
  },
  divider: {
    width: '100%',
    height: 2, 
    backgroundColor: Colors.screenBase,
  },
  entry: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    padding: 8,
  },
  icon: {
    paddingLeft: 8,
    paddingRight: 16,
  },
  locationSet: {
    fontSize: 16,
    color: Colors.text,
    fontFamily: 'roboto',
    flex: 1,
  },
  locationUnset: {
    fontSize: 16,
    color: Colors.inputPlaceholder,
    fontFamily: 'roboto',
    fontStyle: 'italic',
  },
  descriptionSet: {
    fontSize: 16,
    color: Colors.text,
    fontFamily: 'roboto',
    flex: 1,
  },
  descriptionUnset: {
    fontSize: 16,
    color: Colors.inputPlaceholder,
    fontFamily: 'roboto',
    fontStyle: 'italic',
  },
  visibleLabel: {
    fontSize: 16,
    color: Colors.text,
    fontFamily: 'roboto',
  },
  track: {
    false: Colors.idleFill,
    true: Colors.activeFill,
  },
  visibleSwitch: {
    transform: [{ scaleX: .6 }, { scaleY: .6 }],
  },
  trigger: {
    triggerTouchable: {
      activeOpacity: 70,
    },
  },
  options: {
    backgroundColor: Colors.areaBase,
    borderWidth: 0.2,
    borderColor: Colors.areaBorder,
  },
  option: {
    padding: 6,
    color: Colors.text,
    backgroundColor: Colors.areaBase,
    fontFamily: 'roboto',
    fontSize: 16,
    textAlign: 'center',
  },
  modalOverlay: {
    display: 'flex',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContainer: {
    backgroundColor: Colors.modalBase,
    width: '80%',
    maxWidth: 400,
    display: 'flex',
    alignItems: 'center',
    borderRadius: 8,
  },
  modalClose: {
    position: 'absolute',
    width: '100%',
    display: 'flex',
    alignItems: 'flex-end',
  },
  dismissButton: {
    padding: 12,
  },
  modalHeader: {
    fontSize: 18,
    paddingTop: 16,
    paddingBottom: 16,
    color: Colors.labelText,
    fontFamily: 'Roboto',
  },
  modalInput: {
    marginRight: 16,
    marginLeft: 16,
    marginTop: 8,
    marginBottom: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  field: {
    input: {
      backgroundColor: Colors.inputBase,
      color: Colors.inputText,
      borderRadius: 8,
      minHeight: 48,
      maxHeight: 128,
      paddingLeft: 8,
    },
    label: {
      height: 16,
      paddingLeft: 8,
    },
    labelText: {
      color: Colors.inputPlaceholder,
      fontSize: 12,
    },
    container: {
      width: '100%',
      paddingLeft: 16,
      paddingRight: 16,
      paddingTop: 8,
    },
  },
  floatingInput: {
    color: Colors.inputText,
    paddingTop: 20,
    paddingBottom: 4,
  },
  floatingLabel: {
    color: Colors.text,
  },
  floatingCustomLabel: {
    colorFocused: Colors.inputPlaceholder,
    colorBlurred: Colors.inputPlaceholder,
    fontSizeFocused: 12,
  },
  floatingContainer: {
    paddingHorizontal: 12,
    backgroundColor: Colors.inputBase,
    width: '100%',
    borderRadius: 8,
    minHeight: 48,
    maxHeight: 128,
  },
  buttons: {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    padding: 8,
    alignItem: 'flex-end',
    justifyContent: 'flex-end',
  },
  cancelButton: {
    marginTop: 8,
    marginBottom: 16,
    marginRight: 16,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 4,
    backgroundColor: Colors.cancelButton,
    width: '33%',
    height: 32,
    display: 'flex',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: Colors.cancelButtonText,
    fontFamily: 'Roboto',
  },
  saveButton: {
    marginTop: 8,
    marginBottom: 16,
    marginRight: 16,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 4,
    backgroundColor: Colors.primaryButton,
    width: '33%',
    height: 32,
    display: 'flex',
    alignItems: 'center',
  },
  saveButtonText: {
    color: Colors.primaryButtonText,
    fontFamily: 'Roboto',
  },
});

