FROM golang:alpine

RUN apk add build-base imagemagick sqlite ffmpeg curl

RUN mkdir -p /opt/databag
RUN mkdir -p /var/lib/databag
RUN mkdir -p /app/databag/net

RUN mkdir -p /tmp/databag-go-cache
WORKDIR /tmp/databag-go-cache
COPY go.mod go.sum ./
RUN go mod download

WORKDIR /
RUN rm -rf /tmp/databag-go-cache
