/*
 * DataBag
 *
 * DataBag provides storage for decentralized identity based self-hosting apps. It is intended to support sharing of personal data and hosting group conversations. 
 *
 * API version: 0.0.1
 * Contact: roland.osborne@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
  "gorm.io/gorm"
  "gorm.io/driver/sqlite"
	app "databag/internal"
  store "databag/internal/store"
)

func main() {

  db, err := gorm.Open(sqlite.Open("databag.db"), &gorm.Config{})
  if err != nil {
    panic("failed to connect database")
  }
  store.AutoMigrate(db);

	log.Printf("Server started")

	router := app.NewRouter(db)

	log.Fatal(http.ListenAndServe(":7000", router))
}
