---
version: "2.1"
services:
  databag:
    image: balzack/databag:latest
    container_name: databag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "7000:7000"
    volumes:
      - $HOME/appdata/databag:/var/lib/databag
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag
    container_name: databag-ssl-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=YOURDOMAIN.COM
      - SUBDOMAINS=databag,
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
      - STAGING=false #optional
    volumes:
      - $HOME/appdata/swag:/config
      - $PWD/net/container/ssl-proxy.conf:/config/nginx/proxy-confs/databag.subdomain.conf
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
